name: safetyzoness
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  # Firebase (All compatible with firebase_core ^2.24.2)
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.5.6

  # HTTP and API
  http: ^1.1.0
  dio: ^5.3.2
  js: ^0.7.2
  # State Management
  provider: ^6.1.1

  # Utilities
  shared_preferences: ^2.2.2
  connectivity_plus: 6.1.4
  image_picker: ^1.0.4
  uuid: ^4.2.1

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: false
  image_path: "lib/assets/images/logo.jpeg"

flutter:
  uses-material-design: true

  assets:
    - lib/assets/images/logo.jpeg
