name: safetyzoness
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  # Firebase - Updated to latest compatible versions
  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  cloud_firestore: ^5.6.9
  firebase_storage: ^12.4.7

  # Core utilities
  intl: ^0.20.2

  # Document handling - Updated versions
  path_provider: ^2.1.4
  pdf: ^3.11.1
  share_plus: ^11.0.0
  printing: ^5.14.2
  open_filex: ^4.3.2
  permission_handler: ^12.0.0+1

  # HTTP and API - Updated
  http: ^1.2.2
  dio: ^5.7.0
  # Remove js package as it's discontinued

  # State Management
  provider: ^6.1.2

  # Utilities - Updated versions
  shared_preferences: ^2.3.4
  connectivity_plus: ^6.1.4
  image_picker: ^1.1.2
  uuid: ^4.5.1

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0  # Updated
  flutter_launcher_icons: ^0.14.4  # Updated

flutter_icons:
  android: true
  ios: false
  image_path: "lib/assets/images/logo.jpeg"

flutter:
  uses-material-design: true

  assets:
    - lib/assets/images/logo.jpeg