// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWJ7GxoKymrUYba8sJdgy67-3zvJaAfn0',
    appId: '1:827198019651:web:e30a0a46f7d5474ed59cf6',
    messagingSenderId: '827198019651',
    projectId: 'safetyzoness',
    authDomain: 'safetyzoness.firebaseapp.com',
    storageBucket: 'safetyzoness.firebasestorage.app',
    measurementId: 'G-DDB9K6YJSB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWJ7GxoKymrUYba8sJdgy67-3zvJaAfn0',
    appId: '1:827198019651:android:YOUR_ANDROID_APP_ID',
    messagingSenderId: '827198019651',
    projectId: 'safetyzoness',
    storageBucket: 'safetyzoness.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWJ7GxoKymrUYba8sJdgy67-3zvJaAfn0',
    appId: '1:827198019651:ios:YOUR_IOS_APP_ID',
    messagingSenderId: '827198019651',
    projectId: 'safetyzoness',
    storageBucket: 'safetyzoness.firebasestorage.app',
    iosBundleId: 'com.example.safetyzoness',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWJ7GxoKymrUYba8sJdgy67-3zvJaAfn0',
    appId: '1:827198019651:macos:YOUR_MACOS_APP_ID',
    messagingSenderId: '827198019651',
    projectId: 'safetyzoness',
    storageBucket: 'safetyzoness.firebasestorage.app',
    iosBundleId: 'com.example.safetyzoness',
  );
}