// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWJ7GxoKymrUYba8sJdgy67-3zvJaAfn0',
    appId: '1:827198019651:web:4172d9d9f01db5c3d59cf6',
    messagingSenderId: '827198019651',
    projectId: 'safetyzoness',
    authDomain: 'safetyzoness.firebaseapp.com',
    storageBucket: 'safetyzoness.firebasestorage.app',
    measurementId: 'G-Q1DJC2PQHV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZXN4dYTdNVacOv3JhBjTyv_tjEKF5GSg',
    appId: '1:827198019651:android:731ffd2843a5328ad59cf6',
    messagingSenderId: '827198019651',
    projectId: 'safetyzoness',
    storageBucket: 'safetyzoness.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlSSpp2x1LQampdH735wRrK_UV0LkzRvk',
    appId: '1:827198019651:ios:cd066726926c7a7fd59cf6',
    messagingSenderId: '827198019651',
    projectId: 'safetyzoness',
    storageBucket: 'safetyzoness.firebasestorage.app',
    iosBundleId: 'com.example.gst.safetyzoness.safetyzoness',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWJ7GxoKymrUYba8sJdgy67-3zvJaAfn0',
    appId: '1:827198019651:web:a197f615cc60eb09d59cf6',
    messagingSenderId: '827198019651',
    projectId: 'safetyzoness',
    authDomain: 'safetyzoness.firebaseapp.com',
    storageBucket: 'safetyzoness.firebasestorage.app',
    measurementId: 'G-EF964BDKY4',
  );
}
